//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS2_DoTrongDuc.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS2_DoTrongDuc.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại email.
        /// </summary>
        public static string Error_Duplicate_Email {
            get {
                return ResourceManager.GetString("Error_Duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại mã nhân viên.
        /// </summary>
        public static string Error_Duplicate_EmployeeCode {
            get {
                return ResourceManager.GetString("Error_Duplicate_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại số chứng minh thư - thẻ căn cước.
        /// </summary>
        public static string Error_Duplicate_Identification {
            get {
                return ResourceManager.GetString("Error_Duplicate_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại số điện thoại.
        /// </summary>
        public static string Error_Duplicate_PhoneNumber {
            get {
                return ResourceManager.GetString("Error_Duplicate_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được phép để trống. .
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép để trống.
        /// </summary>
        public static string Error_Required_Email {
            get {
                return ResourceManager.GetString("Error_Required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        public static string Error_Required_EmployeeCode {
            get {
                return ResourceManager.GetString("Error_Required_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh thư - thẻ căn cước không được phép để trống.
        /// </summary>
        public static string Error_Required_Identification {
            get {
                return ResourceManager.GetString("Error_Required_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được phép để trống.
        /// </summary>
        public static string Error_Required_Name {
            get {
                return ResourceManager.GetString("Error_Required_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép để trống.
        /// </summary>
        public static string Error_Required_Phone {
            get {
                return ResourceManager.GetString("Error_Required_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai kiểu email.
        /// </summary>
        public static string Error_Type_Email {
            get {
                return ResourceManager.GetString("Error_Type_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai kiểu căn cước công dân.
        /// </summary>
        public static string Error_Type_Identification {
            get {
                return ResourceManager.GetString("Error_Type_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai kiểu số điện thoại.
        /// </summary>
        public static string Error_Type_PhoneNumber {
            get {
                return ResourceManager.GetString("Error_Type_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thất bại..
        /// </summary>
        public static string Msg_Add_Employee_Fail {
            get {
                return ResourceManager.GetString("Msg_Add_Employee_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thành công..
        /// </summary>
        public static string Msg_Add_Employee_Success {
            get {
                return ResourceManager.GetString("Msg_Add_Employee_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thất bại. .
        /// </summary>
        public static string Msg_Delete_Employee_Fali {
            get {
                return ResourceManager.GetString("Msg_Delete_Employee_Fali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công. .
        /// </summary>
        public static string Msg_Delete_Employee_Success {
            get {
                return ResourceManager.GetString("Msg_Delete_Employee_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy ra nhân viên thành công. .
        /// </summary>
        public static string Msg_Get_Employee_Success {
            get {
                return ResourceManager.GetString("Msg_Get_Employee_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tồn tại nhân viên.
        /// </summary>
        public static string Msg_No_Exist_Employee {
            get {
                return ResourceManager.GetString("Msg_No_Exist_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công..
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhân viên thành công. .
        /// </summary>
        public static string Msg_Update_Employee_Success {
            get {
                return ResourceManager.GetString("Msg_Update_Employee_Success", resourceCulture);
            }
        }
    }
}
